const uefi = @import("../uefi.zig");
const Header = @import("header.zig").Header;
const NotYetImplementedFn = uefi.NotYetImplementedFn;
const Guid = uefi.Guid;
const Status = uefi.Status;
const ucs2 = uefi.ucs2;

pub const BootServices = extern struct {
    pub const signature = 0x56524553544f4f42;
    hdr: Header,
    raiseTpl: NotYetImplementedFn,
    restoreTpl: NotYetImplementedFn,
    allocatePages: NotYetImplementedFn,
    freePages: NotYetImplementedFn,
    getMemoryMap: extern fn (memory_map_size: *usize, memory_map: [*]uefi.MemoryDescriptor, map_key: *usize, desc_size: *usize, desc_version: *u32) Status,
    allocatePool: extern fn (pool_type: uefi.MemoryType, size: usize, buf: **c_void) Status,
    freePool: extern fn (buf: *c_void) Status,
    createEvent: NotYetImplementedFn,
    setTimer: NotYetImplementedFn,
    waitForEvent: NotYetImplementedFn,
    signalEvent: NotYetImplementedFn,
    closeEvent: NotYetImplementedFn,
    checkEvent: NotYetImplementedFn,
    installProtocolInterface: NotYetImplementedFn,
    reinstallProtocolInterface: NotYetImplementedFn,
    uninstallProtocolInterface: NotYetImplementedFn,
    handleProtocol: NotYetImplementedFn,
    reserved: ?*c_void,
    registerProtocolNotify: NotYetImplementedFn,
    locateHandle: NotYetImplementedFn,
    locateDevicePath: NotYetImplementedFn,
    installConfigurationTable: NotYetImplementedFn,
    loadImage: NotYetImplementedFn,
    startImage: NotYetImplementedFn,
    exit: NotYetImplementedFn,
    unloadImage: NotYetImplementedFn,
    exitBootServices: extern fn (image_handle: uefi.Handle, map_key: usize) Status,
    getNextMonotonicCount: NotYetImplementedFn,
    stall: extern fn (microseconds: usize) Status,
    setWatchdogTimer: extern fn (timeout: usize, watchdog_code: u64, data_size: usize, watchdog_data: ?[*]ucs2) Status,
    connectController: NotYetImplementedFn,
    disconnectController: NotYetImplementedFn,
    openProtocol: NotYetImplementedFn,
    closeProtocol: NotYetImplementedFn,
    openProtocolInformation: NotYetImplementedFn,
    protocolsPerHandle: NotYetImplementedFn,
    locateHandleBuffer: NotYetImplementedFn,
    locateProtocol: extern fn (protocol: *const Guid, registration: ?*c_void, interface: *?*c_void) Status,
    installMultipleProtocolInterfaces: NotYetImplementedFn,
    uninstallMultipleProtocolInterfaces: NotYetImplementedFn,
    calculateCrc32: NotYetImplementedFn,
    copyMem: NotYetImplementedFn,
    setMem: NotYetImplementedFn,
    createEventEx: NotYetImplementedFn,
};
