const uefi = @import("../uefi.zig");
const Header = @import("header.zig").Header;
const NotYetImplementedFn = uefi.NotYetImplementedFn;
const Guid = uefi.Guid;
const Status = uefi.Status;
const ucs2 = uefi.ucs2;

pub const BootServices = extern struct {
    pub const signature = 0x56524553544f4f42;
    hdr: Header,
    raise_tpl: NotYetImplementedFn,
    restore_tpl: NotYetImplementedFn,
    allocate_pages: NotYetImplementedFn,
    free_pages: NotYetImplementedFn,
    get_memory_map: extern fn (memory_map_size: *usize, memory_map: [*]uefi.MemoryDescriptor, map_key: *usize, desc_size: *usize, desc_version: *u32) Status,
    allocate_pool: extern fn (pool_type: uefi.MemoryType, size: usize, buf: **c_void) Status,
    free_pool: extern fn (buf: *c_void) Status,
    create_event: NotYetImplementedFn,
    set_timer: NotYetImplementedFn,
    wait_for_event: NotYetImplementedFn,
    signal_event: NotYetImplementedFn,
    close_event: NotYetImplementedFn,
    check_event: NotYetImplementedFn,
    install_protocol_interface: NotYetImplementedFn,
    reinstall_protocol_interface: NotYetImplementedFn,
    uninstall_protocol_interface: NotYetImplementedFn,
    handle_protocol: NotYetImplementedFn,
    reserved: ?*c_void,
    register_protocol_notify: NotYetImplementedFn,
    locate_handle: NotYetImplementedFn,
    locate_device_path: NotYetImplementedFn,
    install_configuration_table: NotYetImplementedFn,
    load_image: NotYetImplementedFn,
    start_image: NotYetImplementedFn,
    exit: NotYetImplementedFn,
    unload_image: NotYetImplementedFn,
    exit_boot_services: extern fn (image_handle: uefi.Handle, map_key: usize) Status,
    get_next_monotonic_count: NotYetImplementedFn,
    stall: extern fn (microseconds: usize) Status,
    set_watchdog_timer: extern fn (timeout: usize, watchdog_code: u64, data_size: usize, watchdog_data: ?[*]ucs2) Status,
    connect_controller: NotYetImplementedFn,
    disconnect_controller: NotYetImplementedFn,
    open_protocol: NotYetImplementedFn,
    close_protocol: NotYetImplementedFn,
    open_protocol_information: NotYetImplementedFn,
    protocols_per_handle: NotYetImplementedFn,
    locate_handle_buffer: NotYetImplementedFn,
    locate_protocol: extern fn (protocol: *const Guid, registration: ?*c_void, interface: *?*c_void) Status,
    install_multiple_protocol_interfaces: NotYetImplementedFn,
    uninstall_multiple_protocol_interfaces: NotYetImplementedFn,
    calculate_crc32: NotYetImplementedFn,
    copy_mem: NotYetImplementedFn,
    set_mem: NotYetImplementedFn,
    create_event_ex: NotYetImplementedFn,
};
